export type NodeType =
    | 'Program'
    | 'Property'
    | 'Literal'
    | 'Identifier'
    | 'BinaryExpression'
    | 'UnaryExpression'
    | 'AssignmentExpression'
    | 'CallExpression'
    | 'ObjectExpression'
    | 'FunctionDeclaration'
    | 'VariableDeclaration'
    | 'IfStatement'
    | 'WhileStatement'
    | 'ForStatement'
    | 'ReturnStatement'
    | 'BlockStatement'
